apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  labels:
    name: laravel-config
  namespace: pingspace
data:
  APP_ENV: "prod"
  APP_KEY: "base64:vw6G2uP8LV22haEERtzr5yDCBraLrMwbxlbSJDA97uk="
  APP_DEBUG: "true"
  APP_LOG: "errorlog"
  APP_LOG_LEVEL: "debug"
  APP_URL: "http://localhost"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_DRIVER: "sync"

