apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ include "mychart.fullname" . }}
spec:
  targets:
  - name: {{ include "mychart.fullname" . }}
  origins:
  - jwt:
      issuer: "https://chghealthcare.oktapreview.com"
      jwksUri: "https://chghealthcare.oktapreview.com/oauth2/v1/keys"
      trigger_rules:
      - excluded_paths:
        - exact: /health
  principalBinding: USE_ORIGIN
