apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-php-api
spec:
  hosts:
  - "php-api.wesaynow.com"
  gateways:
  - php-api
  http:
  - route:
    - destination:
        host: {{ (index .Values.ingress.hosts 0).host | quote }}
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PATCH
      - DELETE
      - PUT
      allowCredentials: false
      allowHeaders:
      - "*"
      maxAge: "24h"
