apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-php-api
spec:
  hosts:
  - "php-api.wesaynow.com"
  gateways:
  - php-api
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: {{ (index .Values.ingress.hosts 0).host | quote }}
        port:
        number: {{ .Values.service.port }}
